type User = {
  first_name: string;
  last_name: string;
  email: string;
  phone: string;
};

export type Parent = User & {
  id: number;
  user_id: number;
  student_count: number;
  credit_balance_info: number;
  billing_address: string;
  notification_preferences: string;
};

export const allParents: Parent[] = [
  {
    id: 1,
    user_id: 101,
    first_name: 'Maria',
    last_name: 'Santos',
    email: 'maria.santos@email.com',
    phone: '(718) 555-0101',
    student_count: 2,
    credit_balance_info: 12,
    billing_address: '3115 1st Ave #APT 2A, Brooklyn, New York(NY), 11210',
    notification_preferences: 'email',
  },
  {
    id: 2,
    user_id: 102,
    first_name: 'James',
    last_name: 'Thompson',
    email: 'james.thompson@email.com',
    phone: '(718) 555-0102',
    student_count: 1,
    credit_balance_info: 7,
    billing_address: '226 Malcolm X Blvd, Brooklyn, New York(NY), 11221',
    notification_preferences: 'email',
  },
  {
    id: 3,
    user_id: 103,
    first_name: 'Aisha',
    last_name: 'Johnson',
    email: 'aisha.johnson@email.com',
    phone: '(718) 555-0103',
    student_count: 3,
    credit_balance_info: 18,
    billing_address: '244 Bainbridge St #4, Brooklyn, New York(NY), 11233',
    notification_preferences: 'email',
  },
  {
    id: 4,
    user_id: 104,
    first_name: 'David',
    last_name: 'Williams',
    email: 'david.williams@email.com',
    phone: '(718) 555-0104',
    student_count: 2,
    credit_balance_info: 5,
    billing_address: '246 Carlton Ave, Brooklyn, New York(NY), 11205',
    notification_preferences: 'email',
  },
  {
    id: 5,
    user_id: 105,
    first_name: 'Fatima',
    last_name: 'Ali',
    email: 'fatima.ali@email.com',
    phone: '(718) 555-0105',
    student_count: 1,
    credit_balance_info: 14,
    billing_address: '257 Adelphi St #6, Brooklyn, New York(NY), 11205',
    notification_preferences: 'email',
  },
  {
    id: 6,
    user_id: 106,
    first_name: 'Robert',
    last_name: 'Chen',
    email: 'robert.chen@email.com',
    phone: '(718) 555-0106',
    student_count: 3,
    credit_balance_info: 20,
    billing_address: '261 Windsor Pl, Brooklyn, New York(NY), 11218',
    notification_preferences: 'email',
  },
  {
    id: 7,
    user_id: 107,
    first_name: 'Patricia',
    last_name: 'Brown',
    email: 'patricia.brown@email.com',
    phone: '(718) 555-0107',
    student_count: 2,
    credit_balance_info: 9,
    billing_address: '2709 Clarendon Rd, Brooklyn, New York(NY), 11226',
    notification_preferences: 'email',
  },
  {
    id: 8,
    user_id: 108,
    first_name: 'Michael',
    last_name: 'Davis',
    email: 'michael.davis@email.com',
    phone: '(718) 555-0108',
    student_count: 1,
    credit_balance_info: 3,
    billing_address: '176 Albany Ave #1R, Brooklyn, New York(NY), 11213',
    notification_preferences: 'email',
  },
  {
    id: 9,
    user_id: 109,
    first_name: 'Sandra',
    last_name: 'Rivera',
    email: 'sandra.rivera@email.com',
    phone: '(718) 555-0109',
    student_count: 3,
    credit_balance_info: 16,
    billing_address: '1381 Linden Blvd, Brooklyn, New York(NY), 11212',
    notification_preferences: 'email',
  },
  {
    id: 10,
    user_id: 110,
    first_name: 'Karen',
    last_name: 'Mitchell',
    email: 'karen.mitchell@email.com',
    phone: '(718) 555-0110',
    student_count: 2,
    credit_balance_info: 11,
    billing_address: '31 Saint Johns Pl, Brooklyn, New York(NY), 11217',
    notification_preferences: 'email',
  },
  {
    id: 11,
    user_id: 111,
    first_name: 'Derek',
    last_name: 'Foster',
    email: 'derek.foster@email.com',
    phone: '(718) 555-0111',
    student_count: 1,
    credit_balance_info: 8,
    billing_address: '191 Ashland Pl #3, Brooklyn, New York(NY), 11217',
    notification_preferences: 'email',
  },
  {
    id: 12,
    user_id: 112,
    first_name: 'Linda',
    last_name: 'Nguyen',
    email: 'linda.nguyen@email.com',
    phone: '(718) 555-0112',
    student_count: 3,
    credit_balance_info: 15,
    billing_address: '6632 L Ave, Brooklyn, New York(NY), 11234',
    notification_preferences: 'email',
  },
  {
    id: 13,
    user_id: 113,
    first_name: 'Anthony',
    last_name: 'Clarke',
    email: 'anthony.clarke@email.com',
    phone: '(718) 555-0113',
    student_count: 2,
    credit_balance_info: 6,
    billing_address: '848 E 28th St, Brooklyn, New York(NY), 11210',
    notification_preferences: 'email',
  },
  {
    id: 14,
    user_id: 114,
    first_name: 'Jasmine',
    last_name: 'Washington',
    email: 'jasmine.washington@email.com',
    phone: '(718) 555-0114',
    student_count: 1,
    credit_balance_info: 10,
    billing_address: '2944 W 5th St, Brooklyn, New York(NY), 11224',
    notification_preferences: 'email',
  },
  {
    id: 15,
    user_id: 115,
    first_name: 'Omar',
    last_name: 'Hassan',
    email: 'omar.hassan@email.com',
    phone: '(718) 555-0115',
    student_count: 3,
    credit_balance_info: 19,
    billing_address: '31 Saint Johns Pl, Brooklyn, New York(NY), 11217',
    notification_preferences: 'email',
  },
  {
    id: 16,
    user_id: 116,
    first_name: 'Christine',
    last_name: 'Lee',
    email: 'christine.lee@email.com',
    phone: '(718) 555-0116',
    student_count: 2,
    credit_balance_info: 4,
    billing_address: '191 Ashland Pl #3, Brooklyn, New York(NY), 11217',
    notification_preferences: 'email',
  },
  {
    id: 17,
    user_id: 117,
    first_name: 'Marcus',
    last_name: 'Green',
    email: 'marcus.green@email.com',
    phone: '(718) 555-0117',
    student_count: 1,
    credit_balance_info: 13,
    billing_address: '6632 L Ave, Brooklyn, New York(NY), 11234',
    notification_preferences: 'email',
  },
  {
    id: 18,
    user_id: 118,
    first_name: 'Diana',
    last_name: 'Perez',
    email: 'diana.perez@email.com',
    phone: '(718) 555-0118',
    student_count: 2,
    credit_balance_info: 7,
    billing_address: '848 E 28th St, Brooklyn, New York(NY), 11210',
    notification_preferences: 'email',
  },
  {
    id: 19,
    user_id: 119,
    first_name: 'Scott',
    last_name: 'Diaz',
    email: 'scott.diaz@email.com',
    phone: '(718) 555-0119',
    student_count: 0,
    credit_balance_info: 0,
    billing_address: '849 W 32nd St, Brooklyn, New York(NY), 11210',
    notification_preferences: 'email',
  },
];

export type Student = User & {
  id: number;
  user_id: number;
  parent_id: number;
  grade: string;
};

export const allStudents: Student[] = [
  // Maria Santos (parent_id: 1) — 2 students
  {
    id: 1,
    user_id: 201,
    parent_id: 1,
    first_name: 'Sofia',
    last_name: 'Santos',
    email: 'sofia.santos@email.com',
    phone: '(718) 555-0201',
    grade: '5th',
  },
  {
    id: 2,
    user_id: 202,
    parent_id: 1,
    first_name: 'Miguel',
    last_name: 'Santos',
    email: 'miguel.santos@email.com',
    phone: '(718) 555-0202',
    grade: '3rd',
  },
  // James Thompson (parent_id: 2) — 1 student
  {
    id: 3,
    user_id: 203,
    parent_id: 2,
    first_name: 'Tyler',
    last_name: 'Thompson',
    email: 'tyler.thompson@email.com',
    phone: '(718) 555-0203',
    grade: '7th',
  },
  // Aisha Johnson (parent_id: 3) — 3 students
  {
    id: 4,
    user_id: 204,
    parent_id: 3,
    first_name: 'Zara',
    last_name: 'Johnson',
    email: 'zara.johnson@email.com',
    phone: '(718) 555-0204',
    grade: '9th',
  },
  {
    id: 5,
    user_id: 205,
    parent_id: 3,
    first_name: 'Kofi',
    last_name: 'Johnson',
    email: 'kofi.johnson@email.com',
    phone: '(718) 555-0205',
    grade: '6th',
  },
  {
    id: 6,
    user_id: 206,
    parent_id: 3,
    first_name: 'Amara',
    last_name: 'Johnson',
    email: 'amara.johnson@email.com',
    phone: '(718) 555-0206',
    grade: '4th',
  },
  // David Williams (parent_id: 4) — 2 students
  {
    id: 7,
    user_id: 207,
    parent_id: 4,
    first_name: 'Emma',
    last_name: 'Williams',
    email: 'emma.williams@email.com',
    phone: '(718) 555-0207',
    grade: '8th',
  },
  {
    id: 8,
    user_id: 208,
    parent_id: 4,
    first_name: 'Ethan',
    last_name: 'Williams',
    email: 'ethan.williams@email.com',
    phone: '(718) 555-0208',
    grade: '5th',
  },
  // Fatima Ali (parent_id: 5) — 1 student
  {
    id: 9,
    user_id: 209,
    parent_id: 5,
    first_name: 'Yusuf',
    last_name: 'Ali',
    email: 'yusuf.ali@email.com',
    phone: '(718) 555-0209',
    grade: '6th',
  },
  // Robert Chen (parent_id: 6) — 3 students
  {
    id: 10,
    user_id: 210,
    parent_id: 6,
    first_name: 'Lily',
    last_name: 'Chen',
    email: 'lily.chen@email.com',
    phone: '(718) 555-0210',
    grade: '10th',
  },
  {
    id: 11,
    user_id: 211,
    parent_id: 6,
    first_name: 'Kevin',
    last_name: 'Chen',
    email: 'kevin.chen@email.com',
    phone: '(718) 555-0211',
    grade: '7th',
  },
  {
    id: 12,
    user_id: 212,
    parent_id: 6,
    first_name: 'Mei',
    last_name: 'Chen',
    email: 'mei.chen@email.com',
    phone: '(718) 555-0212',
    grade: '4th',
  },
  // Patricia Brown (parent_id: 7) — 2 students
  {
    id: 13,
    user_id: 213,
    parent_id: 7,
    first_name: 'Jaylen',
    last_name: 'Brown',
    email: 'jaylen.brown@email.com',
    phone: '(718) 555-0213',
    grade: '11th',
  },
  {
    id: 14,
    user_id: 214,
    parent_id: 7,
    first_name: 'Aaliyah',
    last_name: 'Brown',
    email: 'aaliyah.brown@email.com',
    phone: '(718) 555-0214',
    grade: '8th',
  },
  // Michael Davis (parent_id: 8) — 1 student
  {
    id: 15,
    user_id: 215,
    parent_id: 8,
    first_name: 'Noah',
    last_name: 'Davis',
    email: 'noah.davis@email.com',
    phone: '(718) 555-0215',
    grade: '5th',
  },
  // Sandra Rivera (parent_id: 9) — 3 students
  {
    id: 16,
    user_id: 216,
    parent_id: 9,
    first_name: 'Isabella',
    last_name: 'Rivera',
    email: 'isabella.rivera@email.com',
    phone: '(718) 555-0216',
    grade: '9th',
  },
  {
    id: 17,
    user_id: 217,
    parent_id: 9,
    first_name: 'Carlos',
    last_name: 'Rivera',
    email: 'carlos.rivera@email.com',
    phone: '(718) 555-0217',
    grade: '6th',
  },
  {
    id: 18,
    user_id: 218,
    parent_id: 9,
    first_name: 'Mia',
    last_name: 'Rivera',
    email: 'mia.rivera@email.com',
    phone: '(718) 555-0218',
    grade: '3rd',
  },
  // Karen Mitchell (parent_id: 10) — 2 students
  {
    id: 19,
    user_id: 219,
    parent_id: 10,
    first_name: 'Jordan',
    last_name: 'Mitchell',
    email: 'jordan.mitchell@email.com',
    phone: '(718) 555-0219',
    grade: '10th',
  },
  {
    id: 20,
    user_id: 220,
    parent_id: 10,
    first_name: 'Paige',
    last_name: 'Mitchell',
    email: 'paige.mitchell@email.com',
    phone: '(718) 555-0220',
    grade: '7th',
  },
  // Derek Foster (parent_id: 11) — 1 student
  {
    id: 21,
    user_id: 221,
    parent_id: 11,
    first_name: 'Lucas',
    last_name: 'Foster',
    email: 'lucas.foster@email.com',
    phone: '(718) 555-0221',
    grade: '8th',
  },
  // Linda Nguyen (parent_id: 12) — 3 students
  {
    id: 22,
    user_id: 222,
    parent_id: 12,
    first_name: 'Chloe',
    last_name: 'Nguyen',
    email: 'chloe.nguyen@email.com',
    phone: '(718) 555-0222',
    grade: '11th',
  },
  {
    id: 23,
    user_id: 223,
    parent_id: 12,
    first_name: 'Ethan',
    last_name: 'Nguyen',
    email: 'ethan.nguyen@email.com',
    phone: '(718) 555-0223',
    grade: '8th',
  },
  {
    id: 24,
    user_id: 224,
    parent_id: 12,
    first_name: 'Ava',
    last_name: 'Nguyen',
    email: 'ava.nguyen@email.com',
    phone: '(718) 555-0224',
    grade: '5th',
  },
  // Anthony Clarke (parent_id: 13) — 2 students
  {
    id: 25,
    user_id: 225,
    parent_id: 13,
    first_name: 'Marcus',
    last_name: 'Clarke',
    email: 'marcus.clarke@email.com',
    phone: '(718) 555-0225',
    grade: '9th',
  },
  {
    id: 26,
    user_id: 226,
    parent_id: 13,
    first_name: 'Priya',
    last_name: 'Clarke',
    email: 'priya.clarke@email.com',
    phone: '(718) 555-0226',
    grade: '6th',
  },
  // Jasmine Washington (parent_id: 14) — 1 student
  {
    id: 27,
    user_id: 227,
    parent_id: 14,
    first_name: 'DeShawn',
    last_name: 'Washington',
    email: 'deshawn.washington@email.com',
    phone: '(718) 555-0227',
    grade: '7th',
  },
  // Omar Hassan (parent_id: 15) — 3 students
  {
    id: 28,
    user_id: 228,
    parent_id: 15,
    first_name: 'Layla',
    last_name: 'Hassan',
    email: 'layla.hassan@email.com',
    phone: '(718) 555-0228',
    grade: '10th',
  },
  {
    id: 29,
    user_id: 229,
    parent_id: 15,
    first_name: 'Adam',
    last_name: 'Hassan',
    email: 'adam.hassan@email.com',
    phone: '(718) 555-0229',
    grade: '7th',
  },
  {
    id: 30,
    user_id: 230,
    parent_id: 15,
    first_name: 'Nadia',
    last_name: 'Hassan',
    email: 'nadia.hassan@email.com',
    phone: '(718) 555-0230',
    grade: '4th',
  },
  // Christine Lee (parent_id: 16) — 2 students
  {
    id: 31,
    user_id: 231,
    parent_id: 16,
    first_name: 'Hannah',
    last_name: 'Lee',
    email: 'hannah.lee@email.com',
    phone: '(718) 555-0231',
    grade: '9th',
  },
  {
    id: 32,
    user_id: 232,
    parent_id: 16,
    first_name: 'Ryan',
    last_name: 'Lee',
    email: 'ryan.lee@email.com',
    phone: '(718) 555-0232',
    grade: '6th',
  },
  // Marcus Green (parent_id: 17) — 1 student
  {
    id: 33,
    user_id: 233,
    parent_id: 17,
    first_name: 'Caleb',
    last_name: 'Green',
    email: 'caleb.green@email.com',
    phone: '(718) 555-0233',
    grade: '8th',
  },
  // Diana Perez (parent_id: 18) — 2 students
  {
    id: 34,
    user_id: 234,
    parent_id: 18,
    first_name: 'Gabriela',
    last_name: 'Perez',
    email: 'gabriela.perez@email.com',
    phone: '(718) 555-0234',
    grade: '5th',
  },
  {
    id: 35,
    user_id: 235,
    parent_id: 18,
    first_name: 'Diego',
    last_name: 'Perez',
    email: 'diego.perez@email.com',
    phone: '(718) 555-0235',
    grade: '3rd',
  },
];
